[0m14:58:13.751647 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CC50E31BA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CC530909A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CC530907F0>]}


============================== 14:58:13.758885 | 49e9365b-021b-4562-91ae-db2c94838be8 ==============================
[0m14:58:13.758885 [info ] [MainThread]: Running with dbt=1.5.11
[0m14:58:13.760970 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\huynh\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:58:13.761973 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\huynh\Desktop\DataWarehouse\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:58:13.762972 [debug] [MainThread]: Command `dbt run` failed at 14:58:13.762972 after 0.07 seconds
[0m14:58:13.763977 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CC50E31BA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CC530907F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CC53090A90>]}
[0m14:58:13.763977 [debug] [MainThread]: Flushing usage events
[0m14:58:38.754110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD8C7F9BA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD8EA3C9A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD8EA3C7F0>]}


============================== 14:58:38.754110 | 0d702dca-e662-46e3-8447-f7fb006808c5 ==============================
[0m14:58:38.754110 [info ] [MainThread]: Running with dbt=1.5.11
[0m14:58:38.754110 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\huynh\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:58:38.754110 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\huynh\Desktop\DataWarehouse\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:58:38.769884 [debug] [MainThread]: Command `dbt run` failed at 14:58:38.769884 after 0.03 seconds
[0m14:58:38.769884 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD8C7F9BA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD8EA3C7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD8EA3CA90>]}
[0m14:58:38.771346 [debug] [MainThread]: Flushing usage events
